export const NUMBER = {type: 'number'} as const;
export const NUMBER_OR_PERCENTAGE = {type: 'string'} as const;
export const NUMBER_OR_PERCENTAGE_OR_AUTO = {type: 'string'} as const;

export const FLEX_SCHEMA = {
    margin: NUMBER_OR_PERCENTAGE_OR_AUTO,
    marginX: NUMBER_OR_PERCENTAGE_OR_AUTO,
    marginY: NUMBER_OR_PERCENTAGE_OR_AUTO,
    marginTop: NUMBER_OR_PERCENTAGE_OR_AUTO,
    marginLeft: NUMBER_OR_PERCENTAGE_OR_AUTO,
    marginRight: NUMBER_OR_PERCENTAGE_OR_AUTO,
    marginBottom: NUMBER_OR_PERCENTAGE_OR_AUTO,
    transformTranslateX: NUMBER,
    transformTranslateY: NUMBER,
    transformTranslateZ: NUMBER,
    transformScaleX: NUMBER,
    transformScaleY: NUMBER,
    transformScaleZ: NUMBER,
    transformRotateX: NUMBER,
    transformRotateY: NUMBER,
    transformRotateZ: NUMBER,
    positionType: {type: 'string', oneOf: ["absolute", "relative", "count"]},
    inset: NUMBER_OR_PERCENTAGE,
    positionTop: NUMBER_OR_PERCENTAGE,
    positionLeft: NUMBER_OR_PERCENTAGE,
    positionRight: NUMBER_OR_PERCENTAGE,
    positionBottom: NUMBER_OR_PERCENTAGE,
    alignContent: {type: 'string', oneOf: ["count", "space-around", "space-between", "baseline", "stretch", "flex-end", "center", "flex-start", "auto"]},
    alignItems: {type: 'string', oneOf: ["count", "space-around", "space-between", "baseline", "stretch", "flex-end", "center", "flex-start", "auto"]},
    alignSelf: {type: 'string', oneOf: ["count", "space-around", "space-between", "baseline", "stretch", "flex-end", "center", "flex-start", "auto"]},
    flexDirection: {type: 'string', oneOf: ["count", "row-reverse", "row", "column-reverse", "column"]},
    flexWrap: {type: 'string', oneOf: ["count", "wrap-reverse", "wrap", "no-wrap"]},
    justifyContent: {type: 'string', oneOf: ["count", "space-around", "space-between", "flex-end", "center", "flex-start", "space-evenly"]},
    flexBasis: NUMBER_OR_PERCENTAGE,
    flexGrow: NUMBER,
    flexShrink: NUMBER,
    width: NUMBER_OR_PERCENTAGE_OR_AUTO,
    height: NUMBER_OR_PERCENTAGE_OR_AUTO,
    minWidth: NUMBER_OR_PERCENTAGE,
    minHeight: NUMBER_OR_PERCENTAGE,
    maxWidth: NUMBER_OR_PERCENTAGE,
    maxHeight: NUMBER_OR_PERCENTAGE,
    aspectRatio: NUMBER,
    border: NUMBER,
    borderX: NUMBER,
    borderY: NUMBER,
    borderTop: NUMBER,
    borderLeft: NUMBER,
    borderRight: NUMBER,
    borderBottom: NUMBER,
    overflow: {type: 'string', oneOf: ["visible", "scroll", "hidden"]},
    padding: NUMBER_OR_PERCENTAGE,
    paddingX: NUMBER_OR_PERCENTAGE,
    paddingY: NUMBER_OR_PERCENTAGE,
    paddingTop: NUMBER_OR_PERCENTAGE,
    paddingLeft: NUMBER_OR_PERCENTAGE,
    paddingRight: NUMBER_OR_PERCENTAGE,
    paddingBottom: NUMBER_OR_PERCENTAGE,
    gap: NUMBER,
    gapRow: NUMBER,
    gapColumn: NUMBER,
} as const;