import { ContainerProperties } from "@pmndrs/uikit";
import { HasProperties } from "./utils";
import { NUMBER_OR_PERCENTAGE_OR_AUTO, NUMBER, oneOf, NUMBER_OR_PERCENTAGE } from "./property-types";

export const FLEX_SCHEMA = {
    margin: NUMBER_OR_PERCENTAGE_OR_AUTO,
    marginX: NUMBER_OR_PERCENTAGE_OR_AUTO,
    marginY: NUMBER_OR_PERCENTAGE_OR_AUTO,
    marginTop: NUMBER_OR_PERCENTAGE_OR_AUTO,
    marginLeft: NUMBER_OR_PERCENTAGE_OR_AUTO,
    marginRight: NUMBER_OR_PERCENTAGE_OR_AUTO,
    marginBottom: NUMBER_OR_PERCENTAGE_OR_AUTO,
    transformTranslateX: NUMBER,
    transformTranslateY: NUMBER,
    transformTranslateZ: NUMBER,
    transformScaleX: NUMBER,
    transformScaleY: NUMBER,
    transformScaleZ: NUMBER,
    transformRotateX: NUMBER,
    transformRotateY: NUMBER,
    transformRotateZ: NUMBER,
    positionType: oneOf(["absolute", "relative", "static"]),
    inset: NUMBER_OR_PERCENTAGE,
    positionTop: NUMBER_OR_PERCENTAGE,
    positionLeft: NUMBER_OR_PERCENTAGE,
    positionRight: NUMBER_OR_PERCENTAGE,
    positionBottom: NUMBER_OR_PERCENTAGE,
    alignContent: oneOf(["space-around", "space-between", "baseline", "stretch", "flex-end", "center", "flex-start", "auto"]),
    alignItems: oneOf(["space-around", "space-between", "baseline", "stretch", "flex-end", "center", "flex-start", "auto"]),
    alignSelf: oneOf(["space-around", "space-between", "baseline", "stretch", "flex-end", "center", "flex-start", "auto"]),
    flexDirection: oneOf(["row-reverse", "row", "column-reverse", "column"]),
    flexWrap: oneOf(["wrap-reverse", "wrap", "no-wrap"]),
    justifyContent: oneOf(["space-around", "space-between", "flex-end", "center", "flex-start", "space-evenly"]),
    flexBasis: NUMBER_OR_PERCENTAGE,
    flexGrow: NUMBER,
    flexShrink: NUMBER,
    width: NUMBER_OR_PERCENTAGE_OR_AUTO,
    height: NUMBER_OR_PERCENTAGE_OR_AUTO,
    minWidth: NUMBER_OR_PERCENTAGE,
    minHeight: NUMBER_OR_PERCENTAGE,
    maxWidth: NUMBER_OR_PERCENTAGE,
    maxHeight: NUMBER_OR_PERCENTAGE,
    aspectRatio: NUMBER,
    overflow: oneOf(["visible", "scroll", "hidden"]),
    padding: NUMBER_OR_PERCENTAGE,
    paddingX: NUMBER_OR_PERCENTAGE,
    paddingY: NUMBER_OR_PERCENTAGE,
    paddingTop: NUMBER_OR_PERCENTAGE,
    paddingLeft: NUMBER_OR_PERCENTAGE,
    paddingRight: NUMBER_OR_PERCENTAGE,
    paddingBottom: NUMBER_OR_PERCENTAGE,
    gap: NUMBER,
    gapRow: NUMBER,
    gapColumn: NUMBER,
} as const satisfies HasProperties<ContainerProperties>;