name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn set version stable
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install ghp-import
      - name: install, build, and test
        run: |
          ./scripts/build-gh-pages.sh
      - name: deploy
        run: ghp-import ./dist -c aframe-components.fern.solutions -p -f
